name: Tests
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        options: ['']
        zig: [local] # master
    runs-on: ${{matrix.os}}
    steps:
      # - run: exit 0
      #   if: ${{ github.event_name == 'schedule' && matrix.zig != 'master' }}
      - uses: actions/checkout@v3
      - run: git config core.symlinks true
      # NOTE: we rely on npm postinstall-ed zig for local zig
      # - uses: goto-bus-stop/setup-zig@v2
      #   if: ${{ matrix.zig != 'local' }}
      #   with:
      #     version: ${{matrix.zig}}
      - run: npm install
      - run: echo "${GITHUB_WORKSPACE}/build/bin/zig" >> $GITHUB_PATH
        if: ${{ matrix.zig == 'local' && matrix.os != 'windows-latest' }}
      - run: echo "${env:GITHUB_WORKSPACE}/build/bin/zig" >> $env:GITHUB_PATH
        if: ${{ matrix.zig == 'local' && matrix.os == 'windows-latest' }}
      - run: zig build test ${{matrix.options}}
      - run: zig build test ${{matrix.options}} -Doptimize=ReleaseFast
      - run: node src/bin/install-zigpkg --options=""
      - run: npm run compile
      - run: npm test
      - run: make lint
      - run: zig build ${{matrix.options}} -p build
      - uses: mxschmitt/action-tmate@v3 # DEBUG
      - run: make example options="${{matrix.options}}"
      - run: make clean && node src/bin/install-zigpkg --zig
      - run: zig build ${{matrix.options}} -p build -Ddynamic
      - run: make c-example options="${{matrix.options}}" dynamic=true
