name: Tests
on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        options: ['', '-Dfoo', '-Dbar', '-Dfoo -Dbar']
        zig: [local, master]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - run: git config core.symlinks true
      # NOTE: we rely on npm postinstall-ed zig for non-master
      - uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.zig == 'master' }}
        with:
          version: ${{matrix.zig}}
      - run: npm install
      - run: echo "${GITHUB_WORKSPACE}/build/bin/zig" >> $GITHUB_PATH
        if: ${{ matrix.zig != 'master' && matrix.os != 'windows-latest' }}
      - run: echo "${env:GITHUB_WORKSPACE}/build/bin/zig" >> $env:GITHUB_PATH
        if: ${{ matrix.zig != 'master' && matrix.os == 'windows-latest' }}
      #- run: zig build ${{matrix.options}} -p build
      #- run: zig build test ${{matrix.options}}
      #- run: zig build test ${{matrix.options}} -Drelease-fast
      #- run: zig build lint
      #- run: npm run compile
      #- run: npm test
      #- run: npm run test:integration
      #- run: npm run lint
      #- run: zig build --build-file src/examples/zig/build.zig run -- 1234
